### Create a new report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make":"ford",
    "model": "model",
    "year":2026,
    "mileage": 10000,  
    "lng": 0,
    "lat":0,
    "price":20000
}

### Approved a report
PATCH http://localhost:3000/reports/10
Content-Type: application/json

{
    "approved": true
}

### Get an estimate for an existing vehicle
GET http://localhost:3000/reports?make=ford&model=model&year=2026&mileage=10000&lng=0&lat=0

